In [ ]:
#no_test
#dependencies

#nlp packages
import spacy
from spacy.util import minibatch, compounding

#manipulation of tables/arrays
import pandas as pd
import numpy as np

#internal imports
from ssda_nlp.collate import *
from ssda_nlp.split_data import *
from ssda_nlp.modeling import *
from ssda_nlp.model_performance_utils import *
from ssda_nlp.xml_parser import *
from ssda_nlp.relationships import *
from ssda_nlp.unstructured2markup import *

In [ ]:
#no_test

trained_model = load_model('models/mat_baut_1', language="es", verbose='True')

Loaded model 'models/mat_baut_1'

In [ ]:
#no_test

demo_df = parse_xml_v2("transcriptions\\15834.xml")
demo_df.head()

,vol_titl,vol_id,fol_id,text,entry_no
0,"Libro 1 de Bautismos de Pardos y Morenos, 1719...",15834,1033,[margin]: Juana. Esc.va Domingo veinte y dos d...,1033-1
1,"Libro 1 de Bautismos de Pardos y Morenos, 1719...",15834,1033,[margin]: Paula. Esc.a Juebes veinte y tres de...,1033-2
2,"Libro 1 de Bautismos de Pardos y Morenos, 1719...",15834,1033,[margin]: Maria Esc.a Miercoles prim.o de feb....,1033-3
3,"Libro 1 de Bautismos de Pardos y Morenos, 1719...",15834,1033,[margin]: Bernardo Esc.vo Domingo nueve de Abr...,1033-4
4,"Libro 1 de Bautismos de Pardos y Morenos, 1719...",15834,1034,[margin]: Fran.co Esc.vo [roto] Abril de mil s...,1034-1

In [ ]:
#no_test

ent_preds_df, metrics_df, per_ent_metrics = test_model(trained_model, demo_df, "entry_no", "text", score_model=False)

In [ ]:
#no_test

pd.set_option("display.max_rows", None, "display.max_columns", None)
ent_preds_df.head(50)

,entry_no,pred_entity,pred_label,pred_start,pred_end
0,1033-1,Juana,PER,10,15
1,1033-1,Esc.va,CHAR,17,23
2,1033-1,Domingo veinte y dos de [roto] y nueve,DATE,24,62
3,1033-1,Thomas de Orvera,PER,66,82
4,1033-1,Juana de nacion,PER,121,136
5,1033-1,Mina,CHAR,137,141
6,1033-1,esclava,CHAR,142,149
7,1033-1,Juan Joseph de Justis,PER,159,180
8,1033-1,P.P.,REL,192,196
9,1033-1,Joseph Salcedo,PER,197,211
10,1033-1,Ana de Santiago,PER,214,229
11,1033-1,Thomas de Orvera,PER,263,279
12,1033-2,Paula,PER,10,15
13,1033-2,Esc.a,CHAR,17,22
14,1033-2,Juebes veinte y tres de feb.o de mil sietec.to...,DATE,23,86
15,1033-2,Thomas de Orvera,PER,90,106
16,1033-2,Paula,PER,145,150
17,1033-2,h.,CHAR,151,153
18,1033-2,Juan Joseph,PER,162,173
19,1033-2,Maria Josepha,PER,177,190
20,1033-2,esc.s,CHAR,191,196
21,1033-2,Capitan D. Luis Hurtado de Mendoza,PER,201,235
22,1033-2,Padrino,REL,243,250
23,1033-2,Bartholome Rixo,PER,251,266
24,1033-2,Thomas de Orvera,PER,290,306
25,1033-3,Maria,PER,10,15
26,1033-3,Esc.a,CHAR,16,21
27,1033-3,Miercoles prim.o de feb.o de mil siete.tos y d...,DATE,22,79
28,1033-3,Thomas de Orvera,PER,83,99
29,1033-3,Maria,PER,136,141
30,1033-3,h.,CHAR,142,144
31,1033-3,"Juan,",PER,151,156
32,1033-3,Josepha,PER,159,166
33,1033-3,esc.s,CHAR,167,172
34,1033-3,Capitan Antonio Benites,PER,177,200
35,1033-3,Madrina,REL,208,215
36,1033-3,Ysabel Mendez,PER,216,229
37,1033-3,Thomas de Orvera,PER,253,269
38,1033-4,Bernardo,PER,10,18
39,1033-4,Esc.vo,CHAR,19,25
40,1033-4,Domingo nueve de Abril de mil sietectos y diez...,DATE,26,80
41,1033-4,Thomas de Orvera,PER,84,100
42,1033-4,Bernardo,PER,136,144
43,1033-4,negro,CHAR,145,150
44,1033-4,adulto,CHAR,151,157
45,1033-4,carabali,CHAR,168,176
46,1033-4,esc.o,CHAR,177,182
47,1033-4,D. Juan Joseph de Justis,PER,186,210
48,1033-4,P.,REL,218,220
49,1033-4,Andres de Morales,PER,221,238